apiVersion: v1
kind: Service
metadata:
  name: nodejs-svc
spec:
  selector:
    app: nodejs
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: felipeagger/hello-world-nodejs:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: '8080'
        ports:
        - containerPort: 8080
